### ISSUE TITLE
Previous Meteorological State is not parsed

### ISSUE THREAD

**Issue by 5fcgdaeb** [mivek/python-metar-taf-parser#54]
Great work on the library, thanks for such a comprehensive effort!

We have noticed that the previous weather state is not taken into account while parsing the METAR Code:
`METAR LTAE 250250Z VRB02KT 9999 BKN030 BKN080 06/05 Q1005 RESHRA NOSIG RMK RWY21 07004KT 040V100`

We don't see anything related to `RESHRA` (past shower rain).

Is this out of scope or are we missing something? We are using the https://www.metar-taf-decoder.com for testing.

**Comment by mivek** [comment]
Hello @5fcgdaeb

The parsing fails due to the `RE` part of the `RESHRA`. The token is not listed in the [federal meteorological handbook](https://www.icams-portal.gov/resources/ofcm/fmh/FMH1/fmh1_2019.pdf).
However I found other sources listing the token as part of the intensity part of a weather part.
The fix is really simple as it is just a enum missing. 

I will push a fix soon, hopefully during the weekend

**Comment by mivek** [comment]
Hello @5fcgdaeb 

I opened a PR fixing the issue. https://www.metar-taf-decoder.com/ uses the [java version](https://github.com/mivek/MetarParser) of the project. I have already merged the fix and deployed the new version.
