### ISSUE TITLE
Altimeter setting parsing defaults to converting to hectopascals 

### ISSUE THREAD

**Issue by cherls** [mivek/python-metar-taf-parser#59]
There are currently two Altimeter commands, `AltimeterCommand` and `AltimeterMercuryCommand`. The latter parses the altimeter setting given in inches of mercury. However, it converts it to hectopascals before setting the altimeter value to the metar object. 

```
metar.altimeter = int(converter.convert_inches_mercury_to_pascal(mercury))
```

This is misleading or can cause confusion because 
* It implicitly changes the numeric value from the original METAR message
* It does not account for the user country since many still use inHg

I recommend creating an altimeter object to 
* preserve the original unit from the original message
* store the numeric value for both units

**Comment by mivek** [comment]
Hello @cherls 

This behaviour is inherited from the early java version of the project when the parser could only parse the altimeter in hectopascals.
When I added the support for the altimeter in mercury I chose not to change the altimeter attribute because it would have introduce a breaking change. This is why I convert the inches of mercury into hectopascals.

I keep the issue open for now and I will try to think of a way of implementing this without introducing breaking changes.
